server:
  port: 8080
  servlet:
    context-path: /
    session:
      persistent: false

spring:
  application:
    name: @artifactId@
    version: @version@

  # datasource
  datasource:
    name: default
    #driver-class-name: org.sqlite.JDBC
    driver-class-name: org.calendar.driver.SQLiteDriver
    #url: jdbc:sqlite:E:\workspace\idea-my\calendar\src\main\resources\db\calendar.db3
    #url: jdbc:sqlite:resource:db/calendar.db3
    url: jdbc:sqlite:${CALENDAR_DB_PATH:calendar.db3}
    username:
    password:

    # 指定使用的数据源
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 池中最大连接数（包括空闲和正在使用的连接）
      maximum-pool-size: 5
      # 池中最小空闲连接数量
      minimum-idle: 1

  # thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  # jackson
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # profiles
  profiles:
    active: @profiles.active@

# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full

    # org.apache.ibatis.logging.nologging.NoLoggingImpl
    # org.apache.ibatis.logging.stdout.StdOutImpl
    # org.apache.ibatis.logging.slf4j.Slf4jImpl
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

  # 指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 0
      # 删除后
      logic-delete-value: 1
